name: create macos

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        build_type: [Debug, Release]
        platform: [x86_64]
        cppstd: [17]
        shared: ['True', 'False']
        override: ['True', 'False']
        secure: ['True', 'False']
        single_object: ['True', 'False']
        exclude:
          - shared: 'True'
            single_object: 'True'
          - override: 'False'
            single_object: 'True'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"
      - run: python -m pip install --upgrade pip conan
        shell: bash
      - run: |
          conan config install https://github.com/conan-io/hooks.git
          conan config set hooks.conan-center
          conan profile new --detect default
        shell: bash
      - run: |
          echo ${{ matrix.os }} ${{ matrix.build_type }} ${{ matrix.platform }} ${{ matrix.cppstd }}, shared: ${{ matrix.shared }}, override: ${{ matrix.override }}, secure: ${{ matrix.secure }}, single_object: ${{ matrix.single_object }}
          cd recipes/mimalloc/all
          conan create -o mimalloc:single_object=${{ matrix.single_object }} -o mimalloc:secure=${{ matrix.secure }} -o mimalloc:override=${{ matrix.override }} -o mimalloc:shared=${{ matrix.shared }} -s build_type=${{ matrix.build_type }} -s arch=${{ matrix.platform }} -s compiler.cppstd=${{ matrix.cppstd }} . mimalloc/1.6.7@ --build=mimalloc --build=missing
        shell: bash
        env:
          CONAN_REQUEST_TIMEOUT: 120
